const createCsvWriter = require('csv-writer').createObjectCsvWriter;

const csvWriter = createCsvWriter({
  path: "./improveSEO/out.csv",
  header: [
    { id: "Handle", title: "Handle" },
    { id: "Title", title: "Title" },
    { id: "", title: "" },
    { id: "Body (HTML)", title: "Body (HTML)" },
    { id: "Vendor", title: "Vendor" },
    { id: "Type", title: "Type" },
    { id: "Tags", title: "Tags" },
    { id: "Published", title: "Published" },
    { id: "Option1 Name", title: "Option1 Name" },
    { id: "Option1 Value", title: "Option1 Value" },
    { id: "Variant SKU", title: "Variant SKU" },
    { id: "Variant Grams", title: "Variant Grams" },
    { id: "Variant Inventory Tracker", title: "Variant Inventory Tracker" },
    { id: "Variant Inventory Qty", title: "Variant Inventory Qty" },
    { id: "Variant Inventory Policy", title: "Variant Inventory Policy" },
    { id: "Variant Fulfillment Service", title: "Variant Fulfillment Service" },
    { id: "Variant Price", title: "Variant Price" },
    { id: "Variant Compare At Price", title: "Variant Compare At Price" },
    { id: "Variant Requires Shipping", title: "Variant Requires Shipping" },
    { id: "Variant Taxable", title: "Variant Taxable" },
    { id: "Variant Barcode", title: "Variant Barcode" },
    { id: "Image Src", title: "Image Src" },
    { id: "Image Position", title: "Image Position" },
    { id: "Image Alt Text", title: "Image Alt Text" },
    { id: "Gift Card", title: "Gift Card" },
    { id: "SEO Title", title: "SEO Title" },
    { id: "SEO Description", title: "SEO Description" },
    { id: "Google Shopping / Google Product Category", title: "Google Shopping / Google Product Category" },
    { id: "Google Shopping / Gender", title: "Google Shopping / Gender" },
    { id: "Google Shopping / Age Group", title: "Google Shopping / Age Group" },
    { id: "Google Shopping / MPN", title: "Google Shopping / MPN" },
    { id: "Google Shopping / AdWords Grouping", title: "Google Shopping / AdWords Grouping" },
    { id: "Google Shopping / AdWords Labels", title: "Google Shopping / AdWords Labels" },
    { id: "Google Shopping / Condition", title: "Google Shopping / Condition" },
    { id: "Google Shopping / Custom Product", title: "Google Shopping / Custom Product" },
    { id: "Google Shopping / Custom Label 0", title: "Google Shopping / Custom Label 0" },
    { id: "Google Shopping / Custom Label 1", title: "Google Shopping / Custom Label 1" },
    { id: "Google Shopping / Custom Label 2", title: "Google Shopping / Custom Label 2" },
    { id: "Google Shopping / Custom Label 3", title: "Google Shopping / Custom Label 3" },
    { id: "Google Shopping / Custom Label 4", title: "Google Shopping / Custom Label 4" },
    { id: "Variant Image", title: "Variant Image" },
    { id: "Variant Weight Unit", title: "Variant Weight Unit" },
    { id: "Variant Tax Code", title: "Variant Tax Code" },
    { id: "Cost per item", title: "Cost per item" },
  ],
});

module.exports = {
  csvWriter
};
